### ISSUE TITLE
selected counts are actually "No. of plants examined"

### ISSUE THREAD

**Issue by michaldrori** [roszenil/CCDBcurator#1]
Hi,

I reviewed the tab delimited text file with the cleaned data from CCDB and I think you should check the following issue. I found it mainly in species from "Index to chromosome numbers in Asteraceae (Asteracea)" and the problem is as follows:
Your script picks the last large number in brackets as the chromosome number when it is actually the number  of plants examined that had a specific chrom count number.
See examples (not sure how many species have the same issue):
  
Pilosella | rubra | 459 | sporophytic | 3x (trihaploid), 5x (pentaploid hybrid), 7x (heptaploid hybrid), 8x (octoploid hybrid), 6x (P. rubra)(26, 33, 3, 20, **459**)
-- | -- | -- | -- | --
Pilosella | rubra | 459 | sporophytic | 27 (trihaploid), 45 (RRROO), 63 (RRROOOO), 72 (RRRRRROO), 54 (RRRRRR)(26, 33, 3, 20, **459**)

Thanks
Michal D.

**Comment by roszenil** [comment]
Hi! Thanks for reporting this issue. This particular pattern has been fixed. As a reminder there might be  many other patterns that CCDBcurator does not include yet so I appreciate your feedback.
